package com.holub.model.cell;

/**
 * 클래스 이름을 기능에 맞추어 바꿔주세요.
 * @author min-uklee
 */
public final class NearestCellsDTO {

  /**
   *
   */
  private Cell north;
  /**
   *
   */
  private Cell south;
  /**
   *
   */
  private Cell east;
  /**
   *
   */
  private Cell west;
  /**
   *
   */
  private Cell northeast;
  /**
   *
   */
  private Cell northwest;
  /**
   *
   */
  private Cell southeast;
  /**
   *
   */
  private Cell southwest;

  /**
   * Must be generated by builder.
   */
  private NearestCellsDTO() {
  }

  /**
   * Builder for NearestCellsDTO.
   */
  public static class NearestCellsDTOBuilder {

    /**
     * building data.
     */
    private NearestCellsDTO dto;

    /**
     *
     */
    public NearestCellsDTOBuilder() {
      dto = new NearestCellsDTO();
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder north(final Cell v) {
      dto.north = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder south(final Cell v) {
      dto.south = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder east(final Cell v) {
      dto.east = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder west(final Cell v) {
      dto.west = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder northeast(final Cell v) {
      dto.northeast = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder northwest(final Cell v) {
      dto.northwest = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder southeast(final Cell v) {
      dto.southeast = v;
      return this;
    }

    /**
     *
     * @param v
     * @return this
     */
    public NearestCellsDTOBuilder southwest(final Cell v) {
      dto.southwest = v;
      return this;
    }

    /**
     *
     * @return built item
     */
    public NearestCellsDTO build() {
      return dto;
    }
  }

  /**
   *
   * @return cell
   */
  public Cell getNorth() {
    return north;
  }

  /**
   *
   * @return cell
   */
  public Cell getSouth() {
    return south;
  }

  /**
   *
   * @return cell
   */
  public Cell getEast() {
    return east;
  }

  /**
   *
   * @return cell
   */
  public Cell getWest() {
    return west;
  }

  /**
   *
   * @return cell
   */
  public Cell getNortheast() {
    return northeast;
  }
  /**
   *
   * @return cell
   */
  public Cell getNorthwest() {
    return northwest;
  }

  /**
   *
   * @return cell
   */
  public Cell getSoutheast() {
    return southeast;
  }

  /**
   *
   * @return cell
   */
  public Cell getSouthwest() {
    return southwest;
  }
}
